sudo: required
language: bash
services:
  - docker

script:
  # build the Docker image
  - docker build -t yast-test-image -f Dockerfile.$DOCKER_TAG .
  # check the Travis script
  - 'if [ "$DOCKER_TAG" = "latest" ]; then docker run -it yast-test-image shellcheck /usr/local/bin/yast-travis-ruby; fi'

env:
  # define the build matrix to build all images in parallel
  - DOCKER_TAG=latest
  - DOCKER_TAG=sle12-sp2
  - DOCKER_TAG=sle12-sp3
  - DOCKER_TAG=sle12-sp4
  - DOCKER_TAG=sle15
  - DOCKER_TAG=sle15-sp1
  - DOCKER_TAG=caasp-1_0
