FROM yastdevel/ruby:sle12-sp2
RUN zypper ar -f -p30 http://download.opensuse.org/repositories/YaST:/CASP:/1.0/SLE_12_SP2/ \
  yast_caasp_1.0

# install packages from the CaaSP repository
RUN zypper --gpg-auto-import-keys --non-interactive dup --no-recommends \
  --from yast_caasp_1.0 && zypper clean -a

# just some smoke tests, make sure YaST...
RUN TERM=xterm yast2 proxy summary && rm -rf /var/log/YaST2/y2log
# ... and rake work properly
RUN rake -r yast/rake -V
